// 정적 프로젝트 데이터 모델 (Notion CMS 기반 lib/notion/projects.ts와 별도)

export interface LocalizedString {
  ko: string
  en: string
}

export interface TechItem {
  name: string
  color?: string
}

export interface ProjectFeature {
  icon?: string
  title: LocalizedString
  description: LocalizedString
}

export interface TimelineItem {
  date: LocalizedString
  title: LocalizedString
  description: LocalizedString
}

export interface StaticProject {
  slug: string
  title: LocalizedString
  description: LocalizedString
  thumbnailUrl?: string
  demoUrl?: string
  sourceUrl?: string
  period: LocalizedString
  techItems: TechItem[]
  overview?: LocalizedString
  overviewBullets?: LocalizedString[]
  problem?: LocalizedString
  timeline?: TimelineItem[]
  features?: ProjectFeature[]
  outcome?: LocalizedString
  outcomeBullets?: LocalizedString[]
  galleryUrls?: string[]
}

const projects: StaticProject[] = [
  {
    slug: 'hijero-me',
    thumbnailUrl: '/images/projects/hijero-me.png',
    demoUrl: 'https://hijero.me',
    sourceUrl: 'https://github.com/hijero/hijero.me',
    title: {
      ko: 'hijero.me — 커스텀 블로그 애플리케이션',
      en: 'hijero.me — Personal Portfolio',
    },
    description: {
      ko: '기술 블로그와 포트폴리오를 하나의 도메인에서 운영하기 위해 직접 개발한 개인 사이트입니다. Next.js App Router, MDX 블로그, Notion API 프로젝트, next-intl 다국어를 하나의 코드베이스에 통합했습니다.',
      en: 'A personal site built from scratch to run a tech blog and portfolio under one domain. Integrates Next.js App Router, MDX blog, Notion API projects, and next-intl multilingual support in a single codebase.',
    },
    period: {
      ko: '2025.05 ~ 현재',
      en: '2025.05 ~ Present',
    },
    techItems: [
      { name: 'Next.js' },
      { name: 'React 19' },
      { name: 'Notion API' },
      { name: 'TypeScript' },
      { name: 'Tailwind CSS v4' },
      { name: 'shadcn/ui' },
      { name: 'next-intl' },
      { name: 'Supabase' },
    ],
    overview: {
      ko: 'Next.js 16+ App Router와 React 19 기반으로 직접 개발한 개인 블로그·포트폴리오 통합 사이트입니다. 쿠키 없이 SHA-256 서버 핑거프린팅으로 조회수를 추적하고, prebuild 훅으로 생성한 정적 JSON 인덱스로 서버 없이 Cmd+K 전역 검색을 구현했습니다. Notion API를 이력서 CMS로 연결하고 ISR로 30분마다 갱신하며, Turborepo 모노레포로 UI 패키지를 분리해 재사용성과 빌드 성능을 함께 확보했습니다.',
      en: 'A personal blog and portfolio built from scratch on Next.js 16+ App Router and React 19. View counts are tracked via SHA-256 server fingerprinting without cookies, and a static JSON index generated by a prebuild hook powers a serverless Cmd+K global search. The Notion API serves as the resume CMS with 30-minute ISR revalidation, while a Turborepo monorepo isolates the UI package for better reusability and build performance.',
    },
    overviewBullets: [
      {
        ko: 'Turborepo 모노레포 + pnpm workspaces — UI 패키지 분리, Turbo 토폴로지 빌드 순서',
        en: 'Turborepo monorepo + pnpm workspaces — UI package isolation, Turbo topology-sorted build order',
      },
      {
        ko: 'next-intl v4: /ko/, /en/ URL 분리, Accept-Language 자동 감지, hreflang·다국어 사이트맵',
        en: 'next-intl v4: /ko/, /en/ URL split, Accept-Language auto-detection, hreflang & multilingual sitemap',
      },
      {
        ko: 'SHA-256(IP|UA|Accept-Language) 서버 핑거프린팅 — 쿠키·개인정보 없이 24h 중복 차단',
        en: 'SHA-256(IP|UA|Accept-Language) server fingerprinting — 24h dedup without cookies or personal data',
      },
      {
        ko: 'prebuild 훅으로 정적 JSON 검색 인덱스 생성 → Cmd+K Command Palette 서버리스 즉시 검색',
        en: 'prebuild hook generates static JSON search index → serverless instant Cmd+K Command Palette search',
      },
    ],
    problem: {
      ko: '블로그·포트폴리오를 분리 운영하면 관리 비용이 두 배가 되고, 다국어·SEO·검색·조회수 추적이 제각각 흩어진다. 하나의 코드베이스에 두 역할을 통합하되 프라이버시 중심 조회수 추적, 서버리스 검색, Notion 기반 이력서 관리까지 커버하는 구조가 필요했다.',
      en: 'Running a blog and portfolio separately doubles maintenance overhead and scatters i18n, SEO, search, and view tracking. A single codebase needed to cover both roles while supporting privacy-first view tracking, serverless search, and Notion-based resume management.',
    },
    timeline: [
      {
        date: { ko: '2026.05.12', en: 'May 12, 2026' },
        title: {
          ko: '프로젝트 초기화 & 다국어 라우팅',
          en: 'Project Init & i18n Routing',
        },
        description: {
          ko: 'next-intl v4로 /ko/, /en/ URL 분리. Turborepo 모노레포 + pnpm workspaces 환경 구성.',
          en: 'Split /ko/ and /en/ URLs via next-intl v4. Set up Turborepo monorepo + pnpm workspaces.',
        },
      },
      {
        date: { ko: '2026.05.13', en: 'May 13, 2026' },
        title: { ko: '내비게이션 시스템', en: 'Navigation System' },
        description: {
          ko: '데스크탑 80px 고정 RailNav, 모바일 Sheet 드로어, PinnedGNB(테마·언어 토글)를 구현',
          en: 'Built desktop RailNav (80px fixed sidebar), mobile Sheet drawer, and PinnedGNB with theme/locale toggle.',
        },
      },
      {
        date: { ko: '2026.05.14', en: 'May 14, 2026' },
        title: { ko: 'MDX 블로그 파이프라인', en: 'MDX Blog Pipeline' },
        description: {
          ko: 'rehype-pretty-code 코드 하이라이팅, rehype-slug TOC 앵커 자동 생성. SSG로 빌드해 로딩 지연 없음.',
          en: 'Code highlighting via rehype-pretty-code, automatic TOC anchors via rehype-slug. Built with SSG for zero loading delay.',
        },
      },
      {
        date: { ko: '2026.05.15', en: 'May 15, 2026' },
        title: {
          ko: '포스트 상세 & Supabase 조회수',
          en: 'Post Detail & Supabase View Count',
        },
        description: {
          ko: 'Supabase로 포스트 조회수를 추적합니다. 24시간 중복 차단 서버 액션, 관련 포스트 태그 추천 구현.',
          en: 'Tracks post view counts via Supabase. Implemented server action with 24h dedup and related-post tag recommendation.',
        },
      },
      {
        date: { ko: '2026.05.18', en: 'May 18, 2026' },
        title: {
          ko: 'Resume & Notion CMS 연동',
          en: 'Resume & Notion CMS Integration',
        },
        description: {
          ko: 'Notion API로 이력서 프로젝트 데이터를 관리합니다. 별도 CMS 없이 Notion 페이지가 단일 진실 공급원.',
          en: 'Manages resume project data via Notion API. Notion pages serve as the single source of truth with no separate CMS.',
        },
      },
      {
        date: { ko: '2026.05.20', en: 'May 20, 2026' },
        title: { ko: '전역 검색 & SEO 배포', en: 'Global Search & SEO Deploy' },
        description: {
          ko: '빌드 시 정적 JSON 인덱스를 생성해 Cmd+K 검색을 서버 없이 구현. Lighthouse 성능 95+, SEO 100 달성 후 Vercel 배포.',
          en: 'Static JSON index at build time enables Cmd+K search with no server. Achieved Lighthouse performance 95+, SEO 100, then deployed to Vercel.',
        },
      },
      {
        date: { ko: '2026.05.27', en: 'May 27, 2026' },
        title: {
          ko: 'Projects 페이지 & 지속 개선',
          en: 'Projects Page & Ongoing Improvements',
        },
        description: {
          ko: '직장/개인 프로젝트 섹션 분리, soloProject 배지, 페이지 전환 애니메이션 추가. 현재도 기능 고도화 중.',
          en: 'Split work/personal project sections, added soloProject badge and page transition animation. Ongoing feature improvements continue.',
        },
      },
    ],
    features: [
      {
        icon: 'Eye',
        title: { ko: '조회수 추적 시스템', en: 'View Count Tracking' },
        description: {
          ko: 'SHA-256(IP|UA|Accept-Language) 서버 핑거프린팅. 쿠키·개인정보 없이 24h 중복 차단. Supabase RPC 트랜잭션 보장.',
          en: 'SHA-256(IP|UA|Accept-Language) server fingerprinting. 24h dedup without cookies or personal data. Supabase RPC transaction guarantee.',
        },
      },
      {
        icon: 'BookOpen',
        title: { ko: 'MDX 블로그 파이프라인', en: 'MDX Blog Pipeline' },
        description: {
          ko: 'rehype-pretty-code 코드 하이라이팅, rehype-slug TOC + IntersectionObserver 실시간 섹션 추적, 태그 교집합 관련 포스트 추천.',
          en: 'rehype-pretty-code syntax highlighting, rehype-slug TOC + IntersectionObserver live section tracking, tag-intersection related post recommendations.',
        },
      },
      {
        icon: 'Search',
        title: { ko: '빌드 타임 검색 인덱스', en: 'Build-time Search Index' },
        description: {
          ko: 'pnpm prebuild 훅으로 MDX 프론트매터 파싱 → 정적 JSON 생성. Cmd+K Command Palette 서버리스 즉시 검색.',
          en: 'pnpm prebuild hook parses MDX frontmatter → generates static JSON. Serverless instant Cmd+K Command Palette search.',
        },
      },
      {
        icon: 'Globe',
        title: { ko: 'next-intl v4 다국어', en: 'next-intl v4 Multilingual' },
        description: {
          ko: '/ko/, /en/ URL 분리. Accept-Language 자동 감지. 빌드 타임 번역 키 강제 검증. hreflang·사이트맵 완비.',
          en: '/ko/, /en/ URL split. Auto Accept-Language detection. Build-time translation key enforcement. hreflang & sitemap complete.',
        },
      },
      {
        icon: 'Database',
        title: { ko: 'Notion CMS ISR 연동', en: 'Notion CMS ISR Integration' },
        description: {
          ko: '@notionhq/client + 지수 백오프(1→2→4s) 재시도. React.cache() 중복 제거. ISR 30분 자동 갱신. 실패 시 정적 fallback.',
          en: '@notionhq/client + exponential backoff (1→2→4s) retries. React.cache() deduplication. 30-min ISR auto-revalidation. Static fallback on failure.',
        },
      },
    ],
    outcome: {
      ko: 'Lighthouse 성능 95+, SEO 100 달성 후 Vercel 배포.',
      en: 'Achieved Lighthouse performance 95+ and SEO 100, then deployed to Vercel.',
    },
    outcomeBullets: [
      {
        ko: 'Lighthouse 성능 95+, SEO 100',
        en: 'Lighthouse performance 95+, SEO 100',
      },
      {
        ko: '다국어 사이트맵 + hreflang으로 검색 엔진 로케일 명시',
        en: 'Multilingual sitemap + hreflang for search engine locale signaling',
      },
      {
        ko: 'OG 태그로 소셜 공유 미리보기 완비',
        en: 'Full Open Graph tags for social sharing previews',
      },
      {
        ko: 'Supabase Free Tier + Vercel으로 서버리스 운영',
        en: 'Serverless operation on Supabase Free Tier + Vercel',
      },
    ],
  },
  {
    slug: 'elevelyn',
    thumbnailUrl: '/images/projects/elevelyn.png',
    demoUrl: 'https://elevelyn.vercel.app/',
    title: {
      ko: '[MLP] Elevelyn — 선생님과 아이들을 위한 맞춤 영어도우미 플랫폼',
      en: '[MLP] Elevelyn — English Helper Service for Teachers and Kids',
    },
    description: {
      ko: '선생님이 단어 목록으로 2분 안에 워크시트를 만들고, 학생은 앱 설치 없이 손글씨를 쓰면 OCR이 자동으로 채점하는 EdTech 서비스',
      en: 'EdTech service where teachers create worksheets from word lists in 2 min, and students write by hand without any app — OCR grades automatically.',
    },
    period: {
      ko: '2025.05 ~ 현재',
      en: '2025.05 ~ Present',
    },
    techItems: [
      { name: 'Next.js' },
      { name: 'React 19' },
      { name: 'Supabase' },
      { name: 'TypeScript' },
      { name: 'Tesseract.js' },
      { name: 'Canvas API' },
      { name: 'Tailwind CSS' },
      { name: 'shadcn/ui' },
      { name: 'Vercel' },
    ],
    overview: {
      ko: '초등 3~6학년 영어 수업에서 단어 쓰기 연습을 디지털로 전환하기 위해 MLP(Minimum Lovable Product) 수준으로 만든 서비스입니다. 교사가 그룹과 단어 쓰기장을 생성하면 랜덤 URL이 발급되고, 학생들은 앱 설치·회원가입 없이 그 URL로 접속해 브라우저 Canvas에 손으로 영단어를 씁니다. Tesseract.js(Google이 관리하는 오픈소스 OCR 엔진, LSTM 신경망 기반)가 학생 브라우저에서 직접 이미지를 인식·채점하며, 교사는 학생별 손글씨와 정오 결과를 대시보드에서 실시간 확인해 오프라인 교정 기회를 얻습니다.',
      en: "An MLP (Minimum Lovable Product) built to digitize English word writing practice for elementary school grades 3–6. Teachers create a group and word worksheet, which issues a random URL; students access it without installing an app or signing up and write English words by hand on a browser Canvas. Tesseract.js (Google-maintained open-source OCR engine, LSTM neural network-based) runs inference directly in the student's browser, while teachers monitor each student's handwriting and correct/incorrect results in real time on a dashboard.",
    },
    overviewBullets: [
      {
        ko: '랜덤 URL + 6자리 초대 코드·QR — 앱 설치 없이 어떤 기기에서도 즉시 참여',
        en: 'Random URL + 6-digit invite code & QR — instant join on any device, no app install required',
      },
      {
        ko: 'Tesseract.js Worker를 학생 브라우저에서 직접 실행 — 채점 서버 비용 $0',
        en: "Tesseract.js Worker runs directly in the student's browser — $0 grading server cost",
      },
      {
        ko: 'Levenshtein 유사도 0.9 임계값으로 흘려 쓴 글씨도 정답 인정',
        en: 'Levenshtein similarity threshold of 0.9 accepts slightly messy handwriting as correct',
      },
      {
        ko: 'Google OAuth 교사 로그인 + 3초 폴링 실시간 제출 현황',
        en: 'Google OAuth teacher login + 3-second polling for real-time submission status',
      },
    ],
    problem: {
      ko: '초등 영어 수업에서 단어 쓰기 연습은 오프라인 종이에 의존하고 교사가 직접 수기로 채점해야 했다. 디지털 교과서를 사용하는 교실에서도 링크 하나로 접속해 브라우저에 손으로 쓰고 즉시 채점받는 도구가 없었다.',
      en: 'Elementary English word-writing practice depended on offline paper and manual teacher grading. Even in classrooms using digital textbooks, no tool existed that let students join via a single link, write by hand in the browser, and receive instant grading.',
    },
    timeline: [
      {
        date: { ko: '2026.04.28', en: '2026.04.28' },
        title: {
          ko: 'Canvas 워크시트 정적 데모',
          en: 'Static Canvas Worksheet Demo',
        },
        description: {
          ko: 'ResizeObserver 기반 5선지 레이아웃 + Pointer Events 드로잉 엔진 + Tesseract.js OCR 초기 통합. DB/Auth 없이 URL params만으로 동작. Vercel 프리뷰로 선생님 Canvas UX 검증.',
          en: 'ResizeObserver-based 5-line staff layout + Pointer Events drawing engine + initial Tesseract.js OCR integration. Runs on URL params alone with no DB or Auth. Teacher Canvas UX validated via Vercel Preview.',
        },
      },
      {
        date: { ko: '2026.05.05', en: '2026.05.05' },
        title: {
          ko: 'Supabase 스키마 & Google OAuth',
          en: 'Supabase Schema & Google OAuth',
        },
        description: {
          ko: 'notes / note_words / note_sessions 3-table 설계. SECURITY DEFINER 함수로 invite_code 안전 조회. Google OAuth + proxy.ts 보호 라우트. 노트 생성 → 초대 코드 발급 플로우 완성.',
          en: '3-table schema (notes / note_words / note_sessions). SECURITY DEFINER function for safe invite_code lookup. Google OAuth + proxy.ts protected routes. Full note creation → invite code issuance flow.',
        },
      },
      {
        date: { ko: '2026.05.11', en: '2026.05.11' },
        title: {
          ko: '학생 플로우 & MLP 완성',
          en: 'Student Flow & MLP Complete',
        },
        description: {
          ko: '초대 코드 입력 → /api/notes/lookup → 워크시트 진입. localStorage UUID 익명 제출. 완료 화면. 실 Supabase 전체 루프 동작.',
          en: 'Invite code entry → /api/notes/lookup → worksheet. localStorage UUID anonymous submission. Completion screen. Full Supabase end-to-end loop working.',
        },
      },
      {
        date: { ko: '2026.05.17', en: '2026.05.17' },
        title: {
          ko: 'Post-MLP (그룹·대시보드·프로필)',
          en: 'Post-MLP (Groups, Dashboard, Profile)',
        },
        description: {
          ko: 'groups 테이블 + notes.group_id 스키마 확장. 그룹별 노트 카드 리스트. 총 참가/완료 지표 대시보드. 프로필 관리 + GNB 탭 네비게이션.',
          en: 'groups table + notes.group_id schema extension. Group-based note card list. Total joined/completed metrics dashboard. Profile management + GNB tab navigation.',
        },
      },
      {
        date: { ko: '현재', en: 'Present' },
        title: {
          ko: 'E2E 테스트 & 관리자 백오피스 개발 중',
          en: 'E2E Testing & Admin Backoffice In Progress',
        },
        description: {
          ko: 'MLP E2E 시나리오 검증 + /admin 백오피스(계정 목록·통계) 구현 예정.',
          en: 'MLP E2E scenario validation + /admin backoffice (account list & stats) planned.',
        },
      },
    ],
    features: [
      {
        icon: 'Zap',
        title: {
          ko: '단어 쓰기장 생성 & URL 발급',
          en: 'Worksheet Creation & URL Issuance',
        },
        description: {
          ko: '그룹·단어 입력 → 랜덤 URL·6자리 초대 코드 자동 생성. 인쇄 불필요. 몇 번의 클릭으로 완료.',
          en: 'Group & word input → random URL + 6-digit invite code auto-generated. No printing needed. Done in a few clicks.',
        },
      },
      {
        icon: 'ScanText',
        title: {
          ko: '클라이언트 OCR 채점 시스템',
          en: 'Client-side OCR Grading System',
        },
        description: {
          ko: 'Tesseract.js Worker 브라우저 실행. devicePixelRatio 고해상도 Canvas → OCR 인식률 향상. Levenshtein 0.9로 흘려 쓴 글씨 허용.',
          en: 'Tesseract.js Worker runs in-browser. High-res Canvas with devicePixelRatio boosts OCR accuracy. Levenshtein 0.9 allows messy handwriting.',
        },
      },
      {
        icon: 'Database',
        title: {
          ko: 'Supabase 스키마 & RLS 설계',
          en: 'Supabase Schema & RLS Design',
        },
        description: {
          ko: 'notes/note_words/note_sessions 3-table 설계. SECURITY DEFINER 함수로 invite_code 안전 검증. anon INSERT RLS로 학생 무로그인 제출.',
          en: '3-table design (notes/note_words/note_sessions). SECURITY DEFINER function for safe invite_code validation. anon INSERT RLS for student login-free submission.',
        },
      },
      {
        icon: 'UserCheck',
        title: {
          ko: '마찰 없는 학생 참여',
          en: 'Frictionless Student Participation',
        },
        description: {
          ko: 'localStorage UUID로 학생 식별. Google 계정·앱 설치 불필요. URL 하나로 즉시 참여.',
          en: 'Student identification via localStorage UUID. No Google account or app install required. Join instantly with one URL.',
        },
      },
      {
        icon: 'Activity',
        title: {
          ko: '실시간 대시보드 & 그룹 관리',
          en: 'Real-time Dashboard & Group Management',
        },
        description: {
          ko: '3초 폴링 완료 카운터. 그룹별 노트 관리. 총 참가/완료 지표 카드. GNB 탭 네비게이션.',
          en: '3-second polling completion counter. Group-based note management. Total joined/completed metric cards. GNB tab navigation.',
        },
      },
    ],
    outcome: {
      ko: '클라이언트 OCR + Vercel + Supabase Free Tier로 운영비 $0. 초등 교실 즉시 도입 가능한 구조로, 홍보·피드백 수렴 후 단어장 퀴즈·말하기 연습 등 콘텐츠 확장 예정.',
      en: '$0 operating cost with client-side OCR + Vercel + Supabase Free Tier. Deployable instantly in elementary classrooms; content expansion (word quizzes, speaking practice) planned after promotion and user feedback.',
    },
    outcomeBullets: [
      {
        ko: '클라이언트 OCR — 사용자 규모 무관하게 서버 비용 $0',
        en: 'Client-side OCR — $0 server cost regardless of user scale',
      },
      {
        ko: 'Vercel + Supabase Free Tier로 운영비 $0',
        en: '$0 operating cost with Vercel + Supabase Free Tier',
      },
      {
        ko: '앱 설치·회원가입 없이 초등 교실 즉시 도입 가능',
        en: 'Immediately deployable in elementary classrooms — no app install or signup required',
      },
      {
        ko: '홍보·피드백 수렴 후 단어장 퀴즈·말하기 연습 등 콘텐츠 확장 예정',
        en: 'Content expansion planned (word quizzes, speaking practice) after promotion and user feedback',
      },
    ],
  },
]

export function getAllProjects(): StaticProject[] {
  return projects
}

export function getProjectBySlug(slug: string): StaticProject | undefined {
  return projects.find((p) => p.slug === slug)
}
