// 정적 프로젝트 데이터 모델 (Notion CMS 기반 lib/notion/projects.ts와 별도)

export interface LocalizedString {
  ko: string
  en: string
}

export interface TechItem {
  name: string
  color?: string
}

export type FeatureIconName =
  | 'Globe'
  | 'BookOpen'
  | 'Search'
  | 'Eye'
  | 'Database'
  | 'Zap'
  | 'ScanText'
  | 'UserCheck'
  | 'Activity'
  | 'Crown'

export interface ProjectFeature {
  icon?: FeatureIconName
  title: LocalizedString
  description: LocalizedString
}

export interface TimelineItem {
  date: LocalizedString
  title: LocalizedString
  description: LocalizedString
}

export interface StaticProject {
  slug: string
  title: LocalizedString
  description: LocalizedString
  thumbnailUrl?: string
  demoUrl?: string
  sourceUrl?: string
  period: LocalizedString
  techItems: TechItem[]
  overview?: LocalizedString
  overviewBullets?: LocalizedString[]
  problem?: LocalizedString
  timeline?: TimelineItem[]
  features?: ProjectFeature[]
  outcome?: LocalizedString
  outcomeBullets?: LocalizedString[]
  galleryUrls?: string[]
}

const projects: StaticProject[] = [
  {
    slug: 'hijero-me',
    thumbnailUrl: '/images/projects/hijero-me.jpg',
    demoUrl: 'https://hijero.me',
    sourceUrl: 'https://github.com/hijero/hijero.me',
    title: {
      ko: 'hijero.me — 개인 브랜딩 홈페이지',
      en: 'hijero.me — Personal Branding Web Application',
    },
    description: {
      ko: '기술 블로그와 포트폴리오를 아울러 직접 구축한 개인 홈페이지. \
Next.js App Router 기반이고, MDX 파일로 블로그를 관리하며, next-intl 다국어 기능, Notion CMS 기능을 담고 있습니다.',
      en: 'A personal site built from scratch to run a tech blog and portfolio under one domain. \
Integrates Next.js App Router, MDX blog, Notion CMS, and next-intl multilingual support in a single codebase.',
    },
    period: {
      ko: '2025.05 ~ 현재',
      en: '2025.05 ~ Present',
    },
    techItems: [
      { name: 'Next.js' },
      { name: 'React 19' },
      { name: 'Notion API' },
      { name: 'TypeScript' },
      { name: 'Tailwind CSS v4' },
      { name: 'shadcn/ui' },
      { name: 'next-intl' },
      { name: 'Supabase' },
    ],
    overview: {
      ko: 'Next.js 16+ App Router와 React 19 기반으로 직접 개발한 개인 블로그·포트폴리오 통합 웹 애플리케이션입니다. \
쿠키 없이 SHA-256 서버 핑거프린팅으로 조회수를 추적하고, prebuild 훅으로 생성한 정적 JSON 인덱스로 전용 검색 서버 없이 Cmd+K와 슬래시(/) 커맨드 기반 전역 검색을 구현했습니다. \
Notion API를 이력서 CMS로 연결하고 ISR로 30분마다 갱신하며, Turborepo 모노레포로 UI 패키지를 분리해 재사용성과 빌드 성능을 함께 확보했습니다.',
      en: 'A personal blog and portfolio built from scratch on Next.js 16+ App Router and React 19. \
View counts are tracked via SHA-256 server fingerprinting without cookies, and a static JSON index generated by a prebuild hook powers a serverless Cmd+K and slash(/) command-based global search. \
The Notion API serves as the resume CMS with 30-minute ISR revalidation, while a Turborepo monorepo isolates the UI package for better reusability and build performance.',
    },
    overviewBullets: [
      {
        ko: 'Turborepo 모노레포 + pnpm workspaces — UI 패키지 분리, Turbo 토폴로지 빌드 순서',
        en: 'Turborepo monorepo + pnpm workspaces — UI package isolation, Turbo topology-sorted build order',
      },
      {
        ko: 'next-intl v4: /ko/, /en/ URL 분리, Accept-Language 자동 감지, hreflang·다국어 사이트맵',
        en: 'next-intl v4: /ko/, /en/ URL split, Accept-Language auto-detection, hreflang & multilingual sitemap',
      },
      {
        ko: 'SHA-256(IP|UA|Accept-Language) 서버 핑거프린팅 — 쿠키·개인정보 없이 24시간 동안 조회수 중복 방지',
        en: 'SHA-256(IP|UA|Accept-Language) server fingerprinting — 24h view count deduplication without cookies or personal data',
      },
      {
        ko: 'prebuild 훅으로 정적 JSON 검색 인덱스 생성 → Cmd+K와 slash(/)를 사용한 전역 Command Palette 검색',
        en: 'prebuild hook generates static JSON search index → serverless instant Cmd+K and slash(/) command-based global search',
      },
    ],
    problem: {
      ko: '그동안 블로그와 포트폴리오를 따로 운영 및 관리 하다보니 리소스 소모와 관리 비용이 두 배가 되는 점이 불편했습니다. \
tistory, velog와 같은 블로그 서비스의 구조를 입맛에 맞게 커스터마이징하면서, 노션으로 관리했던 이력서를 하나로 합쳐서 브랜딩과 관리를 통합하는 나만의 웹사이트가 필요하다고 판단했습니다. \
급속히 발전하고 점점 성숙해져가는 AI 기술을 활용하여 전보다 훨씬 빠르고 탄력적으로 구현할 수 있겠다는 확신이 있었고, AI Native 개발 연습도 함께 도모하고자 본격적으로 계획 및 개발에 착수했습니다.',
      en: 'Managing a blog and portfolio as separate sites meant double the upkeep, and platforms like Tistory or Velog never offered the level of customization I wanted. \
I decided to build a fully owned site that unified my writing, portfolio, and Notion-managed resume under a single branded domain. \
The rapid maturity of AI-assisted development gave me the confidence to pull it off faster than ever before — and became a hands-on playground for AI-native development practice.',
    },
    timeline: [
      {
        date: { ko: '2026.05.12', en: 'May 12, 2026' },
        title: {
          ko: '프로젝트 초기화 & 다국어 라우팅',
          en: 'Project Init & i18n Routing',
        },
        description: {
          ko: 'next-intl v4로 /ko/, /en/ URL 분리. \
Turborepo 모노레포 + pnpm workspaces 환경 구성.',
          en: 'Split /ko/ and /en/ URLs via next-intl v4. \
Set up Turborepo monorepo + pnpm workspaces.',
        },
      },
      {
        date: { ko: '2026.05.13', en: 'May 13, 2026' },
        title: { ko: '내비게이션 시스템', en: 'Navigation System' },
        description: {
          ko: '데스크탑 80px 고정 RailNav, 모바일 Sheet 드로어, PinnedGNB(테마·언어 토글) 구현. \
next-themes 연동으로 시스템 프리퍼런스 기반 다크/라이트 모드 지원.',
          en: 'Built desktop RailNav (80px fixed sidebar), mobile Sheet drawer, and PinnedGNB with theme/locale toggle. \
Wired next-themes for system-preference-aware dark/light mode.',
        },
      },
      {
        date: { ko: '2026.05.14', en: 'May 14, 2026' },
        title: { ko: 'MDX 블로그 파이프라인', en: 'MDX Blog Pipeline' },
        description: {
          ko: 'rehype-pretty-code 코드 하이라이팅, rehype-slug TOC 앵커 자동 생성. \
SSG로 빌드해 로딩 지연 없음.',
          en: 'Code highlighting via rehype-pretty-code, automatic TOC anchors via rehype-slug. \
Built with SSG for zero loading delay.',
        },
      },
      {
        date: { ko: '2026.05.15', en: 'May 15, 2026' },
        title: {
          ko: '포스트 상세 & Supabase 조회수',
          en: 'Post Detail & Supabase View Count',
        },
        description: {
          ko: 'SHA-256(IP|UA|Accept-Language) 서버 핑거프린팅으로 쿠키 없이 조회수 추적. \
24시간 중복 차단 서버 액션, 관련 포스트 태그 교집합 추천 구현.',
          en: 'Implemented cookie-free view tracking via SHA-256(IP|UA|Accept-Language) server fingerprinting. \
24h dedup server action and tag-intersection related post recommendations.',
        },
      },
      {
        date: { ko: '2026.05.18', en: 'May 18, 2026' },
        title: {
          ko: 'Resume & Notion CMS 연동',
          en: 'Resume & Notion CMS Integration',
        },
        description: {
          ko: 'Notion API로 이력서 프로젝트 데이터를 관리합니다. \
별도 CMS 없이 Notion 페이지가 단일 진실 공급원.',
          en: 'Manages resume project data via Notion API. \
Notion pages serve as the single source of truth with no separate CMS.',
        },
      },
      {
        date: { ko: '2026.05.20', en: 'May 20, 2026' },
        title: { ko: '전역 검색 & SEO 배포', en: 'Global Search & SEO Deploy' },
        description: {
          ko: '빌드 시 정적 JSON 인덱스를 생성해 Cmd+K 검색을 서버 없이 구현. \
Lighthouse 성능 95+, SEO 100 달성 후 Vercel 배포.',
          en: 'Static JSON index at build time enables Cmd+K search with no server. \
Achieved Lighthouse performance 95+, SEO 100, then deployed to Vercel.',
        },
      },
      {
        date: { ko: '2026.05.27', en: 'May 27, 2026' },
        title: {
          ko: 'Projects 페이지 & 지속 개선',
          en: 'Projects Page & Ongoing Improvements',
        },
        description: {
          ko: '직장/개인 프로젝트 섹션 분리, soloProject 배지, 페이지 전환 애니메이션 추가. \
현재도 기능 고도화 중.',
          en: 'Split work/personal project sections, added soloProject badge and page transition animation. \
Ongoing feature improvements continue.',
        },
      },
    ],
    features: [
      {
        icon: 'Eye',
        title: { ko: '조회수 추적 시스템', en: 'View Count Tracking' },
        description: {
          ko: 'SHA-256(IP|UA|Accept-Language) 서버 핑거프린팅. \
쿠키·개인정보 없이 24h 내 중복 집계 방지. \
Supabase RPC 트랜잭션 보장.',
          en: 'SHA-256(IP|UA|Accept-Language) server fingerprinting. \
24h dedup without cookies or personal data. \
Supabase RPC transaction guarantee.',
        },
      },
      {
        icon: 'BookOpen',
        title: { ko: 'MDX 블로그 파이프라인', en: 'MDX Blog Pipeline' },
        description: {
          ko: 'rehype-pretty-code 코드 하이라이팅, rehype-slug TOC + IntersectionObserver 실시간 섹션 추적, 태그 교집합 관련 포스트 추천.',
          en: 'rehype-pretty-code syntax highlighting, rehype-slug TOC + IntersectionObserver live section tracking, tag-intersection related post recommendations.',
        },
      },
      {
        icon: 'Search',
        title: { ko: '빌드 타임 검색 인덱스', en: 'Build-time Search Index' },
        description: {
          ko: 'pnpm prebuild 훅으로 MDX 프론트매터 파싱 → 정적 JSON 생성. \
Cmd+K Command Palette 서버리스 즉시 검색.',
          en: 'pnpm prebuild hook parses MDX frontmatter → generates static JSON. \
Serverless instant Cmd+K Command Palette search.',
        },
      },
      {
        icon: 'Globe',
        title: {
          ko: 'next-intl v4 다국어 및 다크모드 지원',
          en: 'next-intl v4 Multilingual & Dark Mode',
        },
        description: {
          ko: '/ko/, /en/ URL 분리. \
Accept-Language 자동 감지. \
빌드 타임 번역 키 강제 검증. \
hreflang·사이트맵 완비와 함께 Light/Dark 다크모드 지원.',
          en: '/ko/, /en/ URL split. \
Auto Accept-Language detection. \
Build-time translation key enforcement. \
hreflang & sitemap complete. Light/Dark mode support.',
        },
      },
      {
        icon: 'Database',
        title: { ko: 'Notion CMS ISR 연동', en: 'Notion CMS ISR Integration' },
        description: {
          ko: '@notionhq/client + 지수 백오프(1→2→4s) 재시도. \
React.cache() 중복 제거. \
ISR 30분 자동 갱신. \
실패 시 정적 fallback.',
          en: '@notionhq/client + exponential backoff (1→2→4s) retries. \
React.cache() deduplication. \
30-min ISR auto-revalidation. \
Static fallback on failure.',
        },
      },
    ],
    outcome: {
      ko: 'Lighthouse 성능 95+, SEO 100을 달성하며 Vercel에 배포했습니다. \
쿠키·개인정보 없는 서버 핑거프린팅 조회수 추적, prebuild 정적 JSON 기반 Cmd+K 전역 검색, \
next-themes 다크/라이트 모드, next-intl v4 한/영 다국어 라우팅, Notion ISR 이력서 CMS를 \
하나의 코드베이스에서 운영 중입니다.',
      en: 'Shipped to Vercel with Lighthouse performance 95+ and SEO 100. \
The site runs cookie-free view tracking via server fingerprinting, a serverless Cmd+K global search \
powered by a static JSON index, dark/light mode via next-themes, bilingual routing with next-intl v4, \
and a Notion-backed resume CMS with ISR — all from a single codebase.',
    },
    outcomeBullets: [
      {
        ko: 'Lighthouse 성능 95+, SEO 100',
        en: 'Lighthouse performance 95+, SEO 100',
      },
      {
        ko: '다국어 사이트맵 + hreflang으로 검색 엔진 로케일 명시',
        en: 'Multilingual sitemap + hreflang for search engine locale signaling',
      },
      {
        ko: 'OG 태그로 소셜 공유 미리보기 완비',
        en: 'Full Open Graph tags for social sharing previews',
      },
      {
        ko: 'Supabase Free Tier + Vercel으로 서버리스 운영',
        en: 'Serverless operation on Supabase Free Tier + Vercel',
      },
      {
        ko: 'SHA-256 서버 핑거프린팅 — 쿠키·개인정보 없이 조회수 중복 방지',
        en: 'Privacy-first view tracking via SHA-256 server fingerprinting — no cookies, no personal data',
      },
      {
        ko: 'Cmd+K 전역 검색 — 서버 없이 정적 JSON 인덱스로 즉시 응답',
        en: 'Serverless Cmd+K global search — instant results from a static JSON index with no backend',
      },
      {
        ko: 'next-themes 다크/라이트 모드 + next-intl v4 한/영 전환 지원',
        en: 'Dark/light mode with next-themes + bilingual (ko/en) routing with next-intl v4',
      },
    ],
  },
  {
    slug: 'emproving',
    thumbnailUrl: '/images/projects/emproving.png',
    demoUrl: 'https://emproving.vercel.app/',
    title: {
      ko: '[MLP] Emproving — 선생님과 아이들을 위한 맞춤 영어도우미 플랫폼',
      en: '[MLP] Emproving — A Tailored English Learning Platform for Teachers & Students',
    },
    description: {
      ko: '누구나 구글 계정으로 손쉽게 가입하여 영어 받아쓰기 단어장을 만들고, 학생들은 별도 가입 없이 초대링크를 통해 접속하여 브라우저에서 손글씨로 단어를 쓰고, OCR 기술을 활용하여 자동으로 채점하는 에듀테크 서비스',
      en: 'An EduTech service that simplifies English dictation: teachers easily create word lists using Google sign-in, and students write words by hand in the browser via a shared link for instant OCR-based grading without registering.',
    },
    period: {
      ko: '2025.05 ~ 현재',
      en: '2025.05 ~ Present',
    },
    techItems: [
      { name: 'Next.js' },
      { name: 'React 19' },
      { name: 'Supabase' },
      { name: 'TypeScript' },
      { name: 'Tesseract.js' },
      { name: 'Canvas API' },
      { name: 'Tailwind CSS' },
      { name: 'shadcn/ui' },
      { name: 'Vercel' },
    ],
    overview: {
      ko: '초등 3~6학년 영어 수업에서 단어 쓰기 연습을 디지털로 전환하기 위해 MLP(Minimum Lovable Product) 수준으로 만든 서비스입니다. \
선생님이 그룹(예: 3학년 1반)과 단어 쓰기장을 생성하면 랜덤 URL이 발급되고, 학생들은 교육용 기기를 사용하여 앱 설치·회원가입 없이 인터넷에서 해당 URL로 접속해 선생님이 입력한 단어들을 펜으로 따라써보며 영어 단어 학습 및 글씨 연습을 수행하는 방식입니다. \
Tesseract.js(Google이 관리하는 오픈소스 OCR 엔진, LSTM 신경망 기반) 기술을 활용해 이미지를 인식·채점하며, 선생님은 학생들이 따라 쓴 글씨와 정답 여부를 선생님 단어장 대시보드에서 실시간으로 확인할 수 있습니다.',
      en: 'This project is an MLP (Minimum Lovable Product) developed to digitize English word writing practice in 3rd to 6th-grade elementary school classrooms in Korea. \
When a teacher creates a class group (e.g., 3rd Grade, Class 1) and a dictation worksheet, a random URL is generated. \
Without any app installation or sign-up, students can access the link on their school-issued devices to practice writing and spelling English words by hand with a stylus or touch input. \
The application leverages Tesseract.js (an open-source OCR engine managed by Google and based on LSTM neural networks) to recognize and grade the handwriting directly in the browser. \
Teachers can then monitor student submissions and check correctness in real time through their dashboard.',
    },
    overviewBullets: [
      {
        ko: '랜덤 URL + QR 코드 — 앱 설치 없이 어떤 기기에서도 즉시 참여',
        en: 'Random URL + QR Code: Instant participation on any device without installing apps',
      },
      {
        ko: '워크시트 4종 — 영어 따라쓰기 · 한국어→영어 쓰기 · 4지 선다 퀴즈 · 역방향 퀴즈',
        en: '4 Worksheet Modes — English handwriting, reverse handwriting, 4-choice quiz, and reverse quiz',
      },
      {
        ko: 'Tesseract.js Worker를 링크 접속 브라우저에서 직접 실행 — 채점 비용 무료',
        en: 'In-browser Tesseract.js Worker: Zero-cost OCR grading executed directly on the client side',
      },
      {
        ko: 'Levenshtein 유사도 0.9 임계값으로 손글씨 정답률 미세 보정',
        en: 'Handwriting Tolerance: Fine-tuned grading accuracy utilizing a Levenshtein distance similarity threshold of 0.9',
      },
      {
        ko: 'Google OAuth 교사 로그인 + 3초 폴링 제출 현황 모니터링',
        en: 'Google OAuth & Real-time Dashboard: Secure teacher authentication combined with 3-second polling for live student submission tracking',
      },
      {
        ko: 'role 기반 /admin 백오피스 — 계정 관리 · 노트 삭제 · 역할 변경 Server Action',
        en: 'Role-gated /admin backoffice — account management, note deletion, and role change via Server Actions',
      },
      {
        ko: '6자리 초대 코드 + URL 이중 공유 — 학생이 코드 입력만으로 즉시 워크시트 진입',
        en: '6-digit invite code + URL dual sharing — students access worksheets instantly by entering a code',
      },
      {
        ko: '/join 페이지 학생 이름 수집 — 쿠키 저장, 제출 현황에서 학생 이름 식별',
        en: '/join page student name collection — stored as a cookie, teacher dashboard identifies submitters by name',
      },
    ],
    problem: {
      ko: '서울시의 경우 초등학교 내 디지털 수업 일환으로 노트북, 태블릿 PC와 같은 전자기기가 보급되었지만 영어 수업 중에 이를 활용할 방안이 마땅치 않았습니다. \
학생들의 영어 손글씨 연습, 영어 퀴즈 등은 여전히 필기구를 사용하거나 오프라인으로 진행될 수밖에 없는 상황이었습니다. \
이에 따라 교사들은 학생들이 쓴 단어들을 일일이 확인하고 채점하는 데 많은 시간을 할애할 수밖에 없었습니다. \
이러한 선생님들의 고충을 해소하면서 아이들이 쉽고 재밌게 인터넷 환경에서 영어를 학습할 수 있는 플랫폼이 있으면 좋겠다는 니즈를 확인하게 되었습니다.',
      en: "In school districts like Seoul, although digital devices such as laptops and tablets have been widely distributed in classrooms, teachers struggled to find practical ways to integrate them into English classes. \
Activities like handwriting practice and quizzes still relied heavily on offline paper and pencils. \
Consequently, teachers spent a significant amount of time manually reviewing and grading every single student's work. \
I identified a strong need to solve this pain point: a lightweight web platform that eliminates grading overhead for teachers while offering students a fun, interactive way to learn English online.",
    },
    timeline: [
      {
        date: { ko: '2026.04.28', en: 'Apr 28, 2026' },
        title: {
          ko: 'Canvas 워크시트 정적 데모',
          en: 'Static Canvas Worksheet Demo',
        },
        description: {
          ko: 'ResizeObserver 기반 5선지 레이아웃 + Pointer Events 드로잉 엔진 + Tesseract.js OCR 초기 통합. \
DB/Auth 없이 URL params만으로 동작. \
Vercel 프리뷰로 선생님 Canvas UX 검증.',
          en: 'Built a ResizeObserver-based 5-line handwriting guide layout, Pointer Events drawing engine, and initial Tesseract.js OCR integration. \
Operating solely on URL parameters without database or authentication, we quickly validated the teacher canvas UX via Vercel Preview.',
        },
      },
      {
        date: { ko: '2026.05.05', en: 'May 5, 2026' },
        title: {
          ko: 'Supabase 스키마 & Google OAuth',
          en: 'Supabase Schema & Google OAuth',
        },
        description: {
          ko: 'notes / note_words / note_sessions 3-table 설계. \
Google OAuth + proxy.ts 보호 라우트. \
노트 생성 → URL 발급 및 참여 현황 실시간 대시보드 확인 플로우 완성.',
          en: 'Designed a 3-table database schema (notes / note_words / note_sessions). \
Secured routes with Google OAuth and proxy.ts. \
Established the core flow from dictation list creation to URL generation and dashboard monitoring.',
        },
      },
      {
        date: { ko: '2026.05.11', en: 'May 11, 2026' },
        title: {
          ko: '학생 플로우 & MLP 완성',
          en: 'Student Flow & MLP Complete',
        },
        description: {
          ko: 'URL 입력 접속 → 워크시트 진입. \
LocalStorage UUID 익명 제출. \
완료 화면. \
실 Supabase 전체 루프 동작.',
          en: 'Completed the student user flow: URL access to worksheet, anonymous submission tracking using localStorage UUIDs, and a completion screen. \
Established a fully functional, end-to-end database loop with Supabase.',
        },
      },
      {
        date: { ko: '2026.05.17', en: 'May 17, 2026' },
        title: {
          ko: 'Post-MLP (그룹·대시보드·프로필)',
          en: 'Post-MLP (Groups, Dashboard, Profile)',
        },
        description: {
          ko: 'groups 테이블 + notes.group_id 스키마 확장. \
그룹별 노트 카드 리스트. \
총 참가/완료 지표 대시보드. \
프로필 관리 + GNB 탭 네비게이션.',
          en: 'Extended the schema to support class groups (groups table + notes.group_id). \
Developed group-specific worksheet lists, a key-metrics dashboard displaying total participation and completion rates, along with profile management and tab-based GNB navigation.',
        },
      },
      {
        date: { ko: '2026.06.07', en: 'Jun 7, 2026' },
        title: {
          ko: '관리자 백오피스 & 전체 완성',
          en: 'Admin Backoffice & Full Feature Complete',
        },
        description: {
          ko: '어드민 CRUD 완성: 선생님 상세 조회, 노트 삭제, 역할 변경, 계정 삭제(cascade). SECURITY DEFINER 함수 + service_role 기반 admin 클라이언트로 권한 분리. Phase 1~4 전체 26개 Tasks 완료.',
          en: 'Completed admin CRUD: teacher detail view, note deletion, role change, and account deletion with cascade. Separated privileges using SECURITY DEFINER functions and a service_role-based admin client. All 26 Tasks across Phase 1~4 complete.',
        },
      },
      {
        date: { ko: '2026.06.10', en: 'Jun 10, 2026' },
        title: {
          ko: '퀴즈 워크시트 타입 추가',
          en: 'Quiz Worksheet Type',
        },
        description: {
          ko: 'notes 스키마에 worksheet_type 컬럼 추가. 영어 단어 보고 한국어 뜻 4지 선다 퀴즈 구현. QuizCard 프로그레스바 + 60초 타이머 + 확인 플로우.',
          en: 'Added worksheet_type column to notes schema. Implemented 4-choice quiz (English word → Korean meaning). QuizCard with progress bar, 60-second timer, and confirmation flow.',
        },
      },
      {
        date: { ko: '2026.06.12', en: 'Jun 12, 2026' },
        title: {
          ko: 'QR 코드 초대 & 프로필 리디자인',
          en: 'QR Code Invite & Profile Redesign',
        },
        description: {
          ko: '초대 대시보드에 QR 코드 표시 + SVG 다운로드 추가. 프로필 페이지 아바타 원형 + 인라인 닉네임 편집으로 리디자인.',
          en: 'Added QR code display and SVG download to the invite dashboard. Redesigned profile page with circular avatar and inline nickname editing.',
        },
      },
      {
        date: { ko: '2026.06.17', en: 'Jun 17, 2026' },
        title: {
          ko: '역방향 워크시트 변형 추가',
          en: 'Reverse Worksheet Variants',
        },
        description: {
          ko: 'reverse_handwriting(한국어 뜻 보고 영어 손글씨)·reverse_quiz(한국어 뜻 보고 영어 4지 선다) 추가. WORKSHEET_TYPE_CONFIG 단일 SSoT로 타입별 설정 관리. 2단계 타입 선택 UI 도입.',
          en: 'Added reverse_handwriting (Korean → English handwriting) and reverse_quiz (Korean → English 4-choice). Centralized type config in WORKSHEET_TYPE_CONFIG. Introduced 2-step worksheet type selector UI.',
        },
      },
    ],
    features: [
      {
        icon: 'Zap',
        title: {
          ko: '단어 쓰기장 생성 & URL/QR 발급',
          en: 'Worksheet Creation & URL / QR Code Issuance',
        },
        description: {
          ko: '그룹 선택·단어 입력 → 워크시트 타입 선택(따라쓰기/역방향 쓰기/퀴즈/역방향 퀴즈) → 랜덤 URL + QR 코드 자동 생성. QR 코드를 칠판에 띄우면 학생이 카메라로 즉시 접속. 인쇄 불필요.',
          en: 'Choose a group, enter words, select a worksheet type (handwriting / reverse handwriting / quiz / reverse quiz), and instantly generate a random URL + QR code. Display the QR on screen — students join via camera scan, no printing needed.',
        },
      },
      {
        icon: 'ScanText',
        title: {
          ko: '따라쓰기 OCR 채점 시스템',
          en: 'Handwriting OCR Grading System',
        },
        description: {
          ko: 'Tesseract.js Worker 브라우저 실행. \
devicePixelRatio 고해상도 Canvas → OCR 인식률 향상. \
Levenshtein 0.9로 흘려 쓴 글씨도 허용',
          en: "Runs a Tesseract.js Worker directly in the browser. \
Uses devicePixelRatio for a high-resolution Canvas to maximize OCR accuracy, and supports a Levenshtein similarity of 0.9 to accommodate natural variations in children's handwriting.",
        },
      },
      {
        icon: 'Database',
        title: {
          ko: 'Supabase 스키마 & RLS 설계',
          en: 'Supabase Schema & RLS Design',
        },
        description: {
          ko: 'notes | note_words | note_sessions DB table 설계. \
anon INSERT RLS로 학생 무로그인 제출',
          en: 'Structured database tables around notes, note_words, and note_sessions. \
Configured Row Level Security (RLS) policies to allow anonymous student submissions without login hurdles.',
        },
      },
      {
        icon: 'UserCheck',
        title: {
          ko: '누구나 동시에 참여 가능',
          en: 'Everyone can participate at the same time',
        },
        description: {
          ko: 'localStorage UUID로 단어장 접속 유저 식별. /join 페이지에서 학생 이름 수집 후 쿠키로 저장. 6자리 초대 코드 또는 URL로 즉시 참여. Google 계정·앱 설치 불필요.',
          en: 'Identifies student sessions via localStorage UUIDs. Collects student names on the /join page and stores them as cookies. Anyone can join instantly via a 6-digit invite code or URL. No Google account or app installation required.',
        },
      },
      {
        icon: 'Activity',
        title: {
          ko: '태블릿/모바일 환경 친화적인 대시보드 & 유저 그룹 관리',
          en: 'Tablet/Mobile Friendly Dashboard & User Group Management',
        },
        description: {
          ko: '3초 폴링 완료 카운터. \
그룹별 노트 관리. \
총 참가/완료 지표 카드. \
제출된 학생 손글씨 이미지와 정답 여부를 대시보드에서 열람 가능. \
GNB 탭 네비게이션.\n학생 이름이 제출 현황과 함께 표시되어 누가 완료했는지 즉시 파악 가능.',
          en: "Equipped with a 3-second polling completion counter, group-based activity lists, overall participation metrics, \
and a submitted-work dashboard where teachers can review each student's handwriting and grading results. \
Intuitive tabbed GNB navigation optimized for mobile and tablet screens.\nStudent names are shown with submissions so teachers can see at a glance who has completed their work.",
        },
      },
      {
        icon: 'Crown',
        title: {
          ko: '관리자 백오피스',
          en: 'Admin Backoffice',
        },
        description: {
          ko: '/admin 라우트에 role 기반 가드. \
계정 목록 + 통계 카드. \
역할 변경 · 노트 삭제 · 계정 삭제(cascade) Server Action. \
Supabase service role 기반 admin 클라이언트로 일반 RLS 우회.',
          en: 'Role-gated /admin route. \
Account list with stats cards. \
Server Actions for role change, note deletion, and cascading account deletion. \
Admin client with Supabase service role privileges bypasses standard RLS.',
        },
      },
    ],
    outcome: {
      ko: '클라이언트 OCR + Vercel + Supabase Free Tier로 상용 서버 운영비 $0. \
따라쓰기·역방향 쓰기·퀴즈·역방향 퀴즈 워크시트 4종 완성(Phase 1~7). \
초등학교 교실 현장, 개인 교습 어디든 즉시 도입 가능한 구조.',
      en: "Achieved $0 in server maintenance fees by utilizing client-side OCR, Vercel, and Supabase's free tier. \
Completed 4 worksheet modes — handwriting, reverse handwriting, quiz, and reverse quiz — across Phase 1~7. \
The architecture is lightweight and ready for immediate deployment in elementary classrooms or private tutoring.",
    },
    outcomeBullets: [
      {
        ko: '클라이언트 OCR — 사용자 규모 무관하게 서버 비용 $0',
        en: 'Client-side OCR processing: Scalable to unlimited users with $0 server overhead',
      },
      {
        ko: 'Vercel + Supabase Free Tier로 운영비 $0',
        en: 'Zero infrastructure cost: Built entirely on Vercel and Supabase Free Tier',
      },
      {
        ko: '앱 설치·회원가입 없이 초등 교실 즉시 도입 가능',
        en: 'No barriers to entry: Deployable instantly in classrooms without app installation or signups',
      },
      {
        ko: '워크시트 4종(따라쓰기·역방향 쓰기·퀴즈·역방향 퀴즈) — Phase 1~7 전체 완료',
        en: '4 worksheet modes (handwriting, reverse handwriting, quiz, reverse quiz) — Phase 1~7 complete',
      },
    ],
    galleryUrls: [
      '/images/projects/emproving/01-landing.png',
      '/images/projects/emproving/02-dashboard.png',
      '/images/projects/emproving/03-create-note.png',
      '/images/projects/emproving/04-invite-code.png',
      '/images/projects/emproving/05-student-canvas.png',
      '/images/projects/emproving/06-result.png',
      '/images/projects/emproving/07-submitted-dashboard.png',
      '/images/projects/emproving/08-join.png',
      '/images/projects/emproving/09-quiz-worksheet.png',
    ],
  },
]

export function getAllProjects(): StaticProject[] {
  return projects
}

export function getProjectBySlug(slug: string): StaticProject | undefined {
  return projects.find((p) => p.slug === slug)
}
